name: BedWars2023-TeamSelector
authors: ["batmann4bot", "pimentelleo", "andrei1058", "OXipro"]
version: ${project.version}
description: Team Selector Add-on for BedWars2023 Minigame.
website: https://andrei1058.dev
main: com.tomkeuper.bedwars.teamselector.Main
softdepend: [BedWars2023, PlaceholderAPI]
api-version: '1.13'